stages:
  build:
    buildTool: "npm"
    buildToolVersion: "N20"
    buildDescriptor: "package.json"
    npmScript: "ci:build"

  additionalTests:
    npmTests:
      buildDescriptor: "package.json"
      npmScript: "ci:test"

  release:
    cfDeploy:
      appName: "aribamcpci"
      strategy: "default"
      apiEndpoint: "https://api.cf.eu10-005.hana.ondemand.com"
      org: "BrainBox Consulting BV_BrainboxConsultingIG"
      space: "dev"
      credential: "cfcreds"
